### ISSUE TITLE
Ignoring existed advancements

### ISSUE THREAD

**Issue by sternschnaube** [2mal3/Advancement-Count#11]
### Minecraft version

1.20.1

### Datapack version

1.0.1

### Expected Behavior

It checks existed advancements and update the number.

I'm not sure if this is a bug, otherwise it would be great to have a check for this.
I play on a very old world and advancements has been already made.

### Actual Behavior

It ignores existed advancements.

### Reproduction Steps

/

**Comment by 2mal3** [comment]
This is not really a feature yet, but it is a good idea. I'll see how I can implement it.

**Comment by sternschnaube** [comment]
Thanks 😊

**Comment by sternschnaube** [comment]
I saw now, that it is incompatible if you display hearts.
Something like this: https://www.planetminecraft.com/data-pack/health/

Or just the two commands:
/scoreboard objectives add health health
/scoreboard objectives setdisplay list health

**Comment by 2mal3** [comment]
Oh, okay. I'll see if I can do something about that.
By the way, I would recommend you to use one issue only for the one bug in the future and not to deal with several in one single issue. It just makes the overall work much easier, since you don't have to discuss two issues in a single thread, for example.

**Comment by sternschnaube** [comment]
I will check the new version later - thank you so much 🥳
